// <auto-generated />
using System;
using JobService.DBContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace JobService.Migrations
{
    [DbContext(typeof(JobContext))]
    partial class JobContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("JobService.Models.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("482be1d9-7c96-4e5d-ad60-707cbd3862d6"),
                            Description = "Web Development, Mobile Development, Desktop Software Developmen, QA & Testing",
                            IsDeleted = false,
                            Name = "Web, Mobile & Software Dev",
                            Status = true
                        },
                        new
                        {
                            Id = new Guid("5bd0d6ab-340d-4f7c-bb3b-55539422cac5"),
                            Description = "Sales & Marketing Strategy",
                            IsDeleted = false,
                            Name = "Sales & Marketing",
                            Status = true
                        },
                        new
                        {
                            Id = new Guid("f4671ba3-0c0c-4adf-95da-af11f816ebe4"),
                            Description = "Design, Writing, Photography & Translator",
                            IsDeleted = false,
                            Name = "Design & Writing",
                            Status = true
                        },
                        new
                        {
                            Id = new Guid("9cd993d3-de91-4cc9-b72a-2988f6be4107"),
                            Description = "Engineering & Architecture",
                            IsDeleted = false,
                            Name = "Engineering & Architecture",
                            Status = true
                        });
                });

            modelBuilder.Entity("JobService.Models.Job", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Cost")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Jobs");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11402986-27fc-4ba6-bd41-dc7bedda3245"),
                            CategoryId = new Guid("482be1d9-7c96-4e5d-ad60-707cbd3862d6"),
                            Cost = 25,
                            Description = "ASP.Net Core and Xamarin developer",
                            Duration = 2,
                            Name = "Back-end developer",
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("ce6ee095-a4b4-464c-9634-2bf2dff0d798"),
                            CategoryId = new Guid("482be1d9-7c96-4e5d-ad60-707cbd3862d6"),
                            Cost = 25,
                            Description = "We need experienced Angular developer for short term project.",
                            Duration = 1,
                            Name = "Angular Developer Needed",
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("97a09511-2607-4e53-a9c7-25716019beaa"),
                            CategoryId = new Guid("5bd0d6ab-340d-4f7c-bb3b-55539422cac5"),
                            Cost = 2000,
                            Description = "Salesperson needed",
                            Duration = 2,
                            Name = "Salesperson",
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("e3901e7a-c0e3-4ae2-bed5-c3821f6e65d1"),
                            CategoryId = new Guid("f4671ba3-0c0c-4adf-95da-af11f816ebe4"),
                            Cost = 30,
                            Description = "Design & Photography needed to build mockup of mobile app",
                            Duration = 4,
                            Name = "Design & Photography",
                            Type = 0
                        });
                });

            modelBuilder.Entity("JobService.Models.Job", b =>
                {
                    b.HasOne("JobService.Models.Category", "Category")
                        .WithMany("Jobs")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("JobService.Models.Category", b =>
                {
                    b.Navigation("Jobs");
                });
#pragma warning restore 612, 618
        }
    }
}
