version: '3.4'

services:
  ocelot-api-gateway:
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "7000:80"
    depends_on:
      - identity-api
      - job-api
      - payment-api

  identity-api:
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - RabbitMQHostName=rabbitmq
      - ConnectionString=Server=identity-MySqlDB; User Id=IdentityService; Database=IdentityServiceDB; Password=identity_service_password; charset=utf8
      - PORT=80
      - GRPC_PORT=81
    ports:
      - "7001:80"
      - "7101:81"
    depends_on:
      - identity-MySqlDB
      - rabbitmq
      
  identity-MySqlDB:
    restart: always
    environment:
      MYSQL_DATABASE: IdentityServiceDB
      MYSQL_USER: IdentityService
      MYSQL_PASSWORD: identity_service_password
      MYSQL_RANDOM_ROOT_PASSWORD: 'identity_service_password'
    ports:
      - "7011:3306"

  job-api:
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - RabbitMQHostName=rabbitmq
      - ConnectionString=Server=job-SqlServerDB; User Id=sa; Database=JobServiceDB; Password=job_service_password; MultipleActiveResultSets=true
    ports:
      - "7002:80"
    depends_on:
      - job-SqlServerDB
      - rabbitmq

  job-SqlServerDB:
    restart: always
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=job_service_password
    ports:
      - "7012:1433"

  payment-api:
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionString=mongodb://payment-mongoDB
      - RabbitMQHostName=rabbitmq
    ports:
      - "7003:80"
    depends_on:
      - payment-mongoDB
      - rabbitmq

  payment-mongoDB:
    restart: always
    volumes:
      - jobs-mongoDB:/data/db
    ports:
      - "7013:27017"

  rabbitmq:
    restart: always
    ports:
      - "7014:15672"
      - "7015:5672"

volumes:
  jobs-mongoDB:
    external: false