version: '3.4'

services:
  ocelot-api-gateway:
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "6000:80"
    build:
      context: .
      dockerfile: src/Ocelot.ApiGateway/Dockerfile
    depends_on:
      - identity-api
      - job-api
      - payment-api

  identity-api:
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "6001:80"
    build:
      context: .
      dockerfile: src/Services/Identity/Identity.API/Dockerfile
    depends_on:
      - identity-MySqlDB
      
  identity-MySqlDB:
    restart: always
    environment:
      MYSQL_DATABASE: IdentityServiceDB
      MYSQL_USER: IdentityService
      MYSQL_PASSWORD: identity_service_password
      MYSQL_RANDOM_ROOT_PASSWORD: 'identity_service_password'
    ports:
      - "6011:3306"

  job-api:
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "6002:80"
    build:
      context: .
      dockerfile: src/Services/Job/Job.API/Dockerfile
    depends_on:
      - job-SqlServerDB

  job-SqlServerDB:
    restart: always
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=job_service_password
    ports:
      - "6012:1433"

  payment-api:
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionString=mongodb://payment-mongoDB
    ports:
      - "6003:80"
    build:
      context: .
      dockerfile: src/Services/Payment/Payment.API/Dockerfile
    depends_on:
      - payment-mongoDB

  payment-mongoDB:
    volumes:
      - jobs-mongoDB:/data/db
    ports:
      - "6013:27017"

volumes:
  jobs-mongoDB:
    external: false