version: '3.4'

services:
  job-api:
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "7001:80"
    build:
      context: .
      dockerfile: src/Services/JobService/Dockerfile
    depends_on:
      - job-SqlServerDB

  job-SqlServerDB:
    restart: always
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=job_service_password

  account-api:
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "7002:80"
    build:
      context: .
      dockerfile: src/Services/AccountService/Dockerfile
    depends_on:
      - account-MySqlDB
      
  account-MySqlDB:
    restart: always
    environment:
      MYSQL_DATABASE: AccountServiceDB
      MYSQL_USER: AccountService
      MYSQL_PASSWORD: account_service_password
      MYSQL_RANDOM_ROOT_PASSWORD: 'account_service_password'

  payment-api:
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionString=mongodb://payment-mongoDB
    ports:
      - "7003:80"
    build:
      context: .
      dockerfile: src/Services/PaymentService/Dockerfile
    depends_on:
       - payment-mongoDB

  payment-mongoDB:
    ports:
      - "27017:27017"

  ocelot-api-gateway:
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "7000:80"
    build:
      context: .
      dockerfile: src/OcelotApiGateway/Dockerfile
    depends_on:
      - job-SqlServerDB
      - job-api
      - account-MySqlDB
      - account-api
      - payment-api