version: '3.4'

services:
  ocelot-api-gateway:
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "6000:80"
    build:
      context: .
      dockerfile: src/OcelotApiGateway/Dockerfile
    depends_on:
      - account-MySqlDB
      - account-api
      - job-SqlServerDB
      - job-api
      - payment-mongoDB
      - payment-api

  account-api:
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "6001:80"
    build:
      context: .
      dockerfile: src/Services/AccountService/Dockerfile
    depends_on:
      - account-MySqlDB
      
  account-MySqlDB:
    restart: always
    environment:
      MYSQL_DATABASE: AccountServiceDB
      MYSQL_USER: AccountService
      MYSQL_PASSWORD: account_service_password
      MYSQL_RANDOM_ROOT_PASSWORD: 'account_service_password'
    ports:
      - "6011:3306"

  job-api:
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "6002:80"
    build:
      context: .
      dockerfile: src/Services/JobService/Dockerfile
    depends_on:
      - job-SqlServerDB

  job-SqlServerDB:
    restart: always
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=job_service_password
    ports:
      - "6012:1433"

  payment-api:
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionString=mongodb://payment-mongoDB
    ports:
      - "6003:80"
    build:
      context: .
      dockerfile: src/Services/PaymentService/Dockerfile
    depends_on:
      - payment-mongoDB

  payment-mongoDB:
    volumes:
      - jobs-mongoDB:/data/db
    ports:
      - "6013:27017"

volumes:
  jobs-mongoDB:
    external: false