apiVersion: apps/v1
kind: Deployment
metadata:
  name: ocelot-apigateway-deployment
  labels:
    component: ocelotapigateway
spec:
  replicas: 1
  selector:
    matchLabels:
      component: ocelotapigateway
  template:
    metadata:
      labels:
        component: ocelotapigateway
    spec:
      containers: 
        - name: apigateway
          image: mirolimmajidov/ocelot.apigateway:latest
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development