apiVersion: apps/v1
kind: Deployment
metadata:
  name: job-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: job-api
  template:
    metadata:
      labels:
        component: job-api
    spec:
      containers: 
        - name: job-api
          image: mirolimmajidov/job.api:latest
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: ConnectionString
              value: Server=job-mssql-persistent; User Id=sa; Database=JobServiceDB; Password=job_service_password; MultipleActiveResultSets=true
            - name: RabbitMQConnection
              value: rabbitmq-service
            - name: EventBusRetryCount
              value: "0"
---
apiVersion: v1
kind: Service
metadata:
  name: job-api-service
spec:
  type: ClusterIP
  selector:
    component: job-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8002