apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: identity-mysql-persistent
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity-mysql-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: mysql
  template:
    metadata:
      labels:
        component: mysql
    spec:
      volumes:
        - name: mysql-storage
          persistentVolumeClaim:
            claimName: identity-mysql-persistent
      containers:
        - name: mysql
          image: mysql:5.7
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-storage
              mountPath: /var/opt/mysql
          env:
            - name: MYSQL_DATABASE
              value: 'IdentityServiceDB'
            - name: MYSQL_USER
              value: 'IdentityService'
            - name: MYSQL_PASSWORD
              value: 'identity_service_password'
            - name: MYSQL_RANDOM_ROOT_PASSWORD
              value: 'identity_service_password'
---
apiVersion: v1
kind: Service
metadata:
  name: identity-mysql-service
spec:
  type: ClusterIP
  selector:
    component: mysql
  ports:
    - port: 3306
      targetPort: 7011