apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: identity-mysql-persistent
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity-mysql-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        component: mysql
    spec:
      volumes:
        - name: mysql-storage
          persistentVolumeClaim:
            claimName: identity-mysql-persistent
      containers:
        - name: mysql
          image: mysql:5.7
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_DATABASE
              value: "IdentityServiceDB"
            - name: MYSQL_USER
              value: "IdentityService"
            - name: MYSQL_PASSWORD
              value: "identity_service_password"
            - name: MYSQL_ROOT_PASSWORD
              value: "identity_service_password"
		  volumeMounts:
			- name: mysql-storage
			  mountPath: /var/lib/mysql
---
apiVersion: v1
kind: Service
metadata:
  name: identity-mysql-service
spec:
  clusterIP: None
  selector:
    component: mysql
  ports:
    - port: 3306
      targetPort: 7011