apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: payment-api
  template:
    metadata:
      labels:
        component: payment-api
    spec:
      containers: 
        - name: payment-api
          image: mirolimmajidov/payment.api:latest
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: ConnectionString
              value: mongodb://payment-mongo-persistent
            - name: RabbitMQHostName
              value: rabbitmq-service
---
apiVersion: v1
kind: Service
metadata:
  name: payment-api-service
spec:
  type: ClusterIP
  selector:
    component: payment-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8003