apiVersion: v1
kind: Service
metadata:
  name: ocelot-apigateway-service
spec:
  type: ClusterIP
  selector:
    component: ocelotapigateway
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000