apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: job-mssql-persistent
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: job-mssql-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: mssql
  template:
    metadata:
      labels:
        component: mssql
    spec:
      containers:
        - name: mssql
          image: mcr.microsoft.com/mssql/server:2019-latest
          ports:
            - containerPort: 1433
          env:
            - name: MSSQL_PID
              value: "Developer"
            - name: SA_PASSWORD
              value: "job_service_password"
            - name: ACCEPT_EULA
              value: "Y"
          volumeMounts:
            - name: mssql-storage
              mountPath: /var/opt/mssql
      volumes:
        - name: mssql-storage
          persistentVolumeClaim:
            claimName: job-mssql-persistent
---
apiVersion: v1
kind: Service
metadata:
  name: job-mssql-service
spec:
  type: ClusterIP
  selector:
    component: mssql
  ports:
    - port: 1433
      targetPort: 7012