// <auto-generated />
using System;
using AccountService.DBContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AccountService.Migrations
{
    [DbContext(typeof(AccountContext))]
    [Migration("20210425115750_accountDB")]
    partial class accountDB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.5");

            modelBuilder.Entity("AccountService.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<bool>("Status")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("eef82b08-13ca-4cae-a64d-c412a26ee3de"),
                            IsDeleted = false,
                            Name = "User 1",
                            Status = true
                        },
                        new
                        {
                            Id = new Guid("19d6a2c8-94c9-48fd-a935-cbb3cadb5d78"),
                            IsDeleted = false,
                            Name = "User 2",
                            Status = true
                        },
                        new
                        {
                            Id = new Guid("d4358276-7e03-4637-8ecf-9c0260208457"),
                            IsDeleted = false,
                            Name = "User 3",
                            Status = true
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
