apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: identity-mysql-persistent
  namespace: jobs
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity-mysql
  namespace: jobs
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:latest
        env:
            - name: MYSQL_DATABASE
              value: "IdentityServiceDB"
            - name: MYSQL_USER
              value: "IdentityService"
            - name: MYSQL_PASSWORD
              value: "identity_service_password"
            - name: MYSQL_ROOT_PASSWORD
              value: "identity_service_password"
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-storage
        persistentVolumeClaim:
            claimName: identity-mysql-persistent
---
apiVersion: v1
kind: Service
metadata:
  name: identity-mysql
  namespace: jobs
spec:
  type: ClusterIP
  selector:
    app: mysql
  ports:
  - port: 3306
    targetPort: mysql