apiVersion: apps/v1
kind: Deployment
metadata:
  name: job-api
  namespace: jobs
spec:
  replicas: 1
  selector:
    matchLabels:
      component: job-api
  template:
    metadata:
      labels:
        component: job-api
    spec:
      containers: 
        - name: job-api
          image: mirolimmajidov/job.api:latest
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: ConnectionString
              value: Server=job-mssql; User Id=sa; Database=JobServiceDB; Password=JobServicePassword@123; MultipleActiveResultSets=true; TrustServerCertificate=True;
            - name: RabbitMQConfigurationInfo__ConnectionString
              value: rabbitmq-message-receiver
          ports:
          - containerPort: 8080
            name: http
---
apiVersion: v1
kind: Service
metadata:
  name: job-api
  namespace: jobs
spec:
  type: LoadBalancer
  selector:
    component: job-api
  ports:
    - protocol: TCP
      port: 7002
      targetPort: http