apiVersion: apps/v1
kind: Deployment
metadata:
  name: ocelot-apigateway
  namespace: jobs
spec:
  replicas: 1
  selector:
    matchLabels:
      component: ocelot-apigateway
  template:
    metadata:
      labels:
        component: ocelot-apigateway
    spec:
      containers: 
        - name: apigateway
          image: mirolimmajidov/ocelot.apigateway:latest
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Production
          ports:
            - containerPort: 8080
              name: http
---
apiVersion: v1
kind: Service
metadata:
  name: ocelot-apigateway
  namespace: jobs
spec:
  type: LoadBalancer
  selector:
    component: ocelot-apigateway
  ports:
    - protocol: TCP
      port: 7000
      targetPort: http