name: Identity service

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore src/Services/Identity/IdentityService.sln
    - name: Build
      run: dotnet build src/Services/Identity/IdentityService.sln --configuration Debug --no-restore
    - name: Run tests
      run: dotnet test src/Services/Identity/IdentityService.sln
