name: Job service

on:
  push:
    branches: [ master ]
    paths:
    - src/Services/Job/**
    - src/Common/**
    - .github/workflows/job_service.yml

  pull_request:
    branches: [ master ]
    paths:
    - src/Services/Job/**
    - src/Common/**
    - .github/workflows/job_service.yml

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'
    - name: Restore dependencies
      run: dotnet restore src/Services/Job/Tests/Job.UnitTests/Job.UnitTests.csproj
    - name: Run tests
      run: dotnet test src/Services/Job/Tests/Job.UnitTests/Job.UnitTests.csproj --logger "console;verbosity=detailed" --blame