name: Payment service

on:
  pull_request:
    branches: [ master ]
    paths:
    - src/Services/Payment/**
    - src/Common/**
    - .github/workflows/payment_service.yml

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'
    - name: Restore dependencies
      run: dotnet restore src/Services/Payment/Tests/Payment.UnitTests/Payment.UnitTests.csproj
    - name: Run tests
      run: dotnet test src/Services/Payment/Tests/Payment.UnitTests/Payment.UnitTests.csproj --logger "console;verbosity=detailed" --blame